import AppKit
import Combine
import CryptoKit

/// One thing that was on the clipboard: text, a link, an image, or files copied in Finder.
struct ClipItem: Codable, Identifiable, Equatable {
    enum Kind: String, Codable { case text, link, image, files }

    var id = UUID()
    var kind: Kind
    var text: String?          // .text / .link
    var paths: [String]?       // .files
    var imageFile: String?     // .image — file name inside ClipboardHistory.imagesDir
    var imageWidth: Int?
    var imageHeight: Int?
    var app: String?           // the app it was copied from
    var appBundle: String?
    var date: Date
    var pinned = false
    var digest: String         // content hash, so copying the same thing twice moves it to the top instead of duplicating

    /// One line for the list.
    var title: String {
        switch kind {
        case .text, .link:
            let t = (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            return t.split(whereSeparator: \.isNewline).first.map(String.init) ?? t
        case .image:
            if let w = imageWidth, let h = imageHeight { return "Image \(w)×\(h)" }
            return "Image"
        case .files:
            let names = (paths ?? []).map { ($0 as NSString).lastPathComponent }
            return names.count <= 1 ? (names.first ?? "File") : "\(names[0]) and \(names.count - 1) more"
        }
    }

    /// What the search field matches against.
    var searchText: String {
        [text, paths?.joined(separator: " "), app, title].compactMap { $0 }.joined(separator: " ")
    }
}

/// Raycast-style clipboard history: watches the general pasteboard, keeps the last N items on disk
/// (~/Library/Application Support/Armada/clipboard), and puts an item back on the clipboard on request.
/// Everything stays local; nothing here is ever sent to Codiv.
@MainActor
final class ClipboardHistory: ObservableObject {
    static let shared = ClipboardHistory()

    @Published private(set) var items: [ClipItem] = []

    private let pb = NSPasteboard.general
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?

    /// Password managers mark their copies with these types (nspasteboard.org); never record them.
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]
    private static let skippedApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop", "com.apple.keychainaccess",
        "com.apple.Passwords", "com.lastpass.LastPass", "com.dashlane.Dashlane",
    ]
    private static let maxTextBytes = 1_000_000
    private static let maxImageBytes = 25_000_000

    static var dir: URL {
        let d = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Armada/clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: d, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        return d
    }
    static var imagesDir: URL {
        let d = dir.appendingPathComponent("images", isDirectory: true)
        try? FileManager.default.createDirectory(at: d, withIntermediateDirectories: true)
        return d
    }
    private static var storeURL: URL { dir.appendingPathComponent("history.json") }

    func start() {
        guard timer == nil else { return }
        load()
        lastChange = pb.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    // MARK: Watching

    private func poll() {
        let change = pb.changeCount
        guard change != lastChange else { return }
        lastChange = change
        guard Settings.shared.clipboardEnabled, let types = pb.types else { return }
        if types.contains(where: { Self.skippedTypes.contains($0.rawValue) }) { return }
        let front = NSWorkspace.shared.frontmostApplication
        if let b = front?.bundleIdentifier, Self.skippedApps.contains(b) { return }
        guard var item = capture() else { return }
        item.app = front?.localizedName
        item.appBundle = front?.bundleIdentifier
        insert(item)
    }

    /// Files first (Finder puts the name on the clipboard too), then text, then images.
    private func capture() -> ClipItem? {
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipItem(kind: .files, paths: paths, date: Date(), digest: Self.hash(Data(paths.joined(separator: "\n").utf8)))
        }
        if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard s.utf8.count <= Self.maxTextBytes else { return nil }
            return ClipItem(kind: Self.isLink(s) ? .link : .text, text: s, date: Date(), digest: Self.hash(Data(s.utf8)))
        }
        if let raw = pb.data(forType: .png) ?? pb.data(forType: .tiff), raw.count <= Self.maxImageBytes,
           let rep = NSBitmapImageRep(data: raw), let png = rep.representation(using: .png, properties: [:]) {
            let digest = Self.hash(png)
            let name = digest.prefix(24) + ".png"
            let url = Self.imagesDir.appendingPathComponent(String(name))
            if !FileManager.default.fileExists(atPath: url.path) { try? png.write(to: url) }
            return ClipItem(kind: .image, imageFile: String(name), imageWidth: rep.pixelsWide, imageHeight: rep.pixelsHigh, date: Date(), digest: digest)
        }
        return nil
    }

    private static func isLink(_ s: String) -> Bool {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains(where: \.isWhitespace), let u = URL(string: t), let scheme = u.scheme?.lowercased() else { return false }
        return ["http", "https"].contains(scheme) && u.host != nil
    }

    private static func hash(_ d: Data) -> String {
        SHA256.hash(data: d).map { String(format: "%02x", $0) }.joined()
    }

    // MARK: Editing

    private func insert(_ new: ClipItem) {
        var item = new
        if let i = items.firstIndex(where: { $0.digest == new.digest }) {
            item.id = items[i].id
            item.pinned = items[i].pinned
            items.remove(at: i)
        }
        items.insert(item, at: 0)
        trim()
        save()
    }

    /// Keeps every pinned item plus the newest unpinned ones up to the limit.
    private func trim() {
        let limit = Settings.shared.clipboardLimit
        var kept = 0
        var dropped: [ClipItem] = []
        items.removeAll { item in
            if item.pinned { return false }
            kept += 1
            if kept > limit { dropped.append(item); return true }
            return false
        }
        dropped.forEach(removeImageIfUnused)
    }

    func delete(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        removeImageIfUnused(item)
        save()
    }

    func togglePin(_ item: ClipItem) {
        guard let i = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[i].pinned.toggle()
        save()
    }

    /// Clears everything except pinned items.
    func clearUnpinned() {
        let gone = items.filter { !$0.pinned }
        items.removeAll { !$0.pinned }
        gone.forEach(removeImageIfUnused)
        save()
    }

    private func removeImageIfUnused(_ item: ClipItem) {
        guard let f = item.imageFile, !items.contains(where: { $0.imageFile == f }) else { return }
        try? FileManager.default.removeItem(at: Self.imagesDir.appendingPathComponent(f))
    }

    // MARK: Using an item

    /// Puts the item back on the clipboard (and moves it to the top, like Raycast). Our own write is not re-recorded.
    func copy(_ item: ClipItem) {
        pb.clearContents()
        switch item.kind {
        case .text, .link:
            pb.setString(item.text ?? "", forType: .string)
        case .files:
            pb.writeObjects((item.paths ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        case .image:
            if let img = image(for: item) {
                pb.writeObjects([img])
                if let f = item.imageFile, let png = try? Data(contentsOf: Self.imagesDir.appendingPathComponent(f)) { pb.setData(png, forType: .png) }
            }
        }
        lastChange = pb.changeCount
        if let i = items.firstIndex(where: { $0.id == item.id }) {
            var moved = items.remove(at: i)
            moved.date = Date()
            items.insert(moved, at: 0)
            save()
        }
    }

    /// Sends ⌘V to the frontmost app. Needs Accessibility; without it the item is simply on the clipboard.
    static func pasteIntoFrontApp() {
        guard AXIsProcessTrusted() else { return }
        let src = CGEventSource(stateID: .combinedSessionState)
        let v: CGKeyCode = 9
        let down = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: true)
        let up = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    private var imageCache: [String: NSImage] = [:]
    func image(for item: ClipItem) -> NSImage? {
        guard let f = item.imageFile else { return nil }
        if let img = imageCache[f] { return img }
        let img = NSImage(contentsOf: Self.imagesDir.appendingPathComponent(f))
        imageCache[f] = img
        return img
    }

    // MARK: Disk

    private func load() {
        guard let data = try? Data(contentsOf: Self.storeURL) else { return }
        let dec = JSONDecoder()
        dec.dateDecodingStrategy = .iso8601
        items = (try? dec.decode([ClipItem].self, from: data)) ?? []
    }

    private func save() {
        let enc = JSONEncoder()
        enc.dateEncodingStrategy = .iso8601
        guard let data = try? enc.encode(items) else { return }
        try? data.write(to: Self.storeURL, options: .atomic)
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: Self.storeURL.path)
    }
}
